name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: 8.2
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

    - name: Install dependencies
      run: |
        composer install --prefer-source --no-interaction
        npm install --legacy-peer-deps --no-audit

    - name: Build Assets
      run: npm run build

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate App Key
      run: php artisan key:generate

    - name: Run PHPUnit tests
      run: php artisan test --parallel
